### ISSUE TITLE
LongRanger crashes

### ISSUE THREAD

**Issue by f0t1h** [aquaskyline/LRSIM#17]
I am trying to align LRSIM simulation with LongRanger. I am getting following error. Any ideas on how to avoid this?

> [error] Pipestance failed. Error log at:
Compgen10XSim/ALIGNER_CS/ALIGNER/_ALIGNER/ATTACH_BCS/fork0/chnk0/_errors
Log message:
Traceback (most recent call last):
  File "/mnt/compgen/inhouse/src/longranger/longranger-2.1.6/martian-cs/2.2.2/adapters/python/main.py", line 23, in <module>
    martian.run("martian.module.main(args, outs)")
  File "/mnt/compgen/inhouse/src/longranger/longranger-2.1.6/martian-cs/2.2.2/adapters/python/martian.py", line 544, in run
    exec(cmd, __main__.__dict__, __main__.__dict__)
  File "<string>", line 1, in <module>
  File "/mnt/compgen/inhouse/src/longranger/longranger-2.1.6/longranger-cs/2.1.6/mro/stages/reads/attach_bcs/__init__.py", line 198, in main
    assert(reads_attached >= 2)
AssertionError

**Comment by aquaskyline** [comment]
This might be related to #19
