### ISSUE TITLE
Long Ranger fails on simulated data

### ISSUE THREAD

**Issue by arshajii** [aquaskyline/LRSIM#3]
I simulated reads using

    perl simulateLinkedReads.pl -r refdata-hg19-2.1.0/fasta/genome.fa -p sim -x 400

and tried running Long Ranger via

    longranger align --id=lrsim --reference=refdata-hg19-2.1.0 --fastqs=lrsim_data --fastqprefix=sim --localcores=12

However, the run fails:

```
...
2017-01-10 12:17:59 [runtime] (run:local)       ID.lrsim.ALIGNER_CS.ALIGNER._ALIGNER.ATTACH_BCS.fork0.chnk37.main
2017-01-10 12:17:59 [runtime] (run:local)       ID.lrsim.ALIGNER_CS.ALIGNER._ALIGNER.ATTACH_BCS.fork0.chnk38.main
2017-01-10 12:17:59 [runtime] (run:local)       ID.lrsim.ALIGNER_CS.ALIGNER._ALIGNER.ATTACH_BCS.fork0.chnk39.main
2017-01-10 12:17:59 [runtime] (run:local)       ID.lrsim.ALIGNER_CS.ALIGNER._ALIGNER.ATTACH_BCS.fork0.chnk40.main
2017-01-10 12:17:59 [runtime] (run:local)       ID.lrsim.ALIGNER_CS.ALIGNER._ALIGNER.ATTACH_BCS.fork0.chnk41.main
2017-01-10 12:18:17 [runtime] (failed)          ID.lrsim.ALIGNER_CS.ALIGNER._ALIGNER.ATTACH_BCS

[error] Pipestance failed. Please see log at:
lrsim/ALIGNER_CS/ALIGNER/_ALIGNER/ATTACH_BCS/fork0/chnk0/_errors
```

The error appears to arise from a failed assertion:

```
Traceback (most recent call last):
  File "/mnt/work/arshajii/10x_aligner/longranger-2.0.1/martian-cs/2.0.1/adapters/python/main.py", line 20, in <module>
    martian.run("martian.module.main(args, outs)")
  File "/mnt/work/arshajii/10x_aligner/longranger-2.0.1/martian-cs/2.0.1/adapters/python/martian.py", line 417, in run
    exec(cmd, __main__.__dict__, __main__.__dict__)
  File "<string>", line 1, in <module>
  File "/mnt/work/arshajii/10x_aligner/longranger-2.0.1/longranger-cs/2.0.1/mro/stages/reads/attach_bcs/__init__.py", line 179, in main
    assert(reads_attached >= 2)
AssertionError
```

**Comment by aquaskyline** [comment]
Yes I encountered the same problem, we will try to figure out what's the problem and it takes longer without the source code of longranger. Meanwhile, would you please try "longranger wgs" mode, we succeed with that.

**Comment by isrbbc** [comment]
Hi, I'm encountering this very same issue. Any updates on running longranger align on simulated data?
Thanks.
