### ISSUE TITLE
running slow at CHECKPOINT 4, Simulate Read Part

### ISSUE THREAD

**Issue by thelingxichen** [aquaskyline/LRSIM#8]
Hi aquaskyline,

When I run a small haplotype fasta for test LRSIM, the programme always stuck for a lot of time at `Fri Sep  8 14:08:37 2017: 100000 reads remaining` in **CHECKPOINT 4, Simulate Read** Part.
```
Fri Sep  8 14:07:55 2017: Simulate reads start
Fri Sep  8 14:07:55 2017: Load barcodes start
Fri Sep  8 14:07:59 2017: Load barcodes end
Fri Sep  8 14:07:59 2017: readPairsPerMolecule: 35
Fri Sep  8 14:07:59 2017: Simulate reads begin on haplotype 0. Total 1
Fri Sep  8 14:07:59 2017: Simulating on haplotype: 0
Fri Sep  8 14:07:59 2017: Load read positions haplotype 0
Fri Sep  8 14:08:02 2017: 0 reads failed being loaded.
Fri Sep  8 14:08:02 2017: Exporting test.0.fp
Fri Sep  8 14:08:02 2017: Exported test.0.fp
Fri Sep  8 14:08:02 2017: readsCountDown: 562554
Fri Sep  8 14:08:07 2017: 500000 reads remaining
Fri Sep  8 14:08:14 2017: 400000 reads remaining
Fri Sep  8 14:08:22 2017: 300000 reads remaining
Fri Sep  8 14:08:30 2017: 200000 reads remaining
Fri Sep  8 14:08:37 2017: 100000 reads remaining
```

And when I stop the programme with Ctrl-C, and rerun the script, the remaining 100000 reads can processed very quickly.

So, why when `100000 reads remaining`, the process time suddenly slow? And, why restart can make the progress faster?
Is it okay to stop and restart the process for a quicker running time? Any effect on simulated result?

Thanks a lot.
Lindsay

**Comment by thelingxichen** [comment]
The initial run log:
```
Fri Sep  8 14:19:24 2017: Simulate reads start
Fri Sep  8 14:19:24 2017: Load barcodes start
Fri Sep  8 14:19:28 2017: Load barcodes end
Fri Sep  8 14:19:28 2017: readPairsPerMolecule: 35
Fri Sep  8 14:19:28 2017: Simulate reads begin on haplotype 0. Total 1
Fri Sep  8 14:19:28 2017: Simulating on haplotype: 0
Fri Sep  8 14:19:28 2017: Load read positions haplotype 0
Fri Sep  8 14:19:33 2017: 0 reads failed being loaded.
Fri Sep  8 14:19:33 2017: Exporting test.0.fp
Fri Sep  8 14:19:33 2017: Exported test.0.fp
Fri Sep  8 14:19:33 2017: readsCountDown: 937208
Fri Sep  8 14:19:34 2017: 900000 reads remaining
Fri Sep  8 14:19:36 2017: 800000 reads remaining
Fri Sep  8 14:19:38 2017: 700000 reads remaining
Fri Sep  8 14:19:41 2017: 600000 reads remaining
Fri Sep  8 14:19:43 2017: 500000 reads remaining
Fri Sep  8 14:19:45 2017: 400000 reads remaining
Fri Sep  8 14:19:48 2017: 300000 reads remaining
Fri Sep  8 14:19:52 2017: 200000 reads remaining
Fri Sep  8 14:20:10 2017: 100000 reads remaining
^CTraceback (most recent call last):
  File "../simulate.py", line 96, in <module>
    run_LRSIM(hap_fasta, prefix, args)
  File "../simulate.py", line 67, in run_LRSIM
    subprocess.call(cmd, shell=True)
  File "/disk2/workspace/chenlingxi/workspace/Bio_Projects/10X_Pipeline/anaconda2-4.4.0/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/disk2/workspace/chenlingxi/workspace/Bio_Projects/10X_Pipeline/anaconda2-4.4.0/lib/python2.7/subprocess.py", line 1073, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/disk2/workspace/chenlingxi/workspace/Bio_Projects/10X_Pipeline/anaconda2-4.4.0/lib/python2.7/subprocess.py", line 121, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
```

The rerun log:
```
Fri Sep  8 14:21:35 2017: Simulate reads start
Fri Sep  8 14:21:35 2017: Load barcodes start
Fri Sep  8 14:21:38 2017: Load barcodes end
Fri Sep  8 14:21:38 2017: readPairsPerMolecule: 35
Fri Sep  8 14:21:38 2017: Simulate reads begin on haplotype 0. Total 1
Fri Sep  8 14:21:38 2017: Simulating on haplotype: 0
Fri Sep  8 14:21:38 2017: Load read positions haplotype 0
Fri Sep  8 14:21:38 2017: Importing test.0.fp
Fri Sep  8 14:21:38 2017: Imported test.0.fp
Fri Sep  8 14:21:38 2017: readsCountDown: 484219
Fri Sep  8 14:21:40 2017: 400000 reads remaining
Fri Sep  8 14:21:43 2017: 300000 reads remaining
Fri Sep  8 14:21:45 2017: 200000 reads remaining
Fri Sep  8 14:21:48 2017: 100000 reads remaining
Fri Sep  8 14:21:50 2017: 0 reads remaining
```
I noticed that readsCountDown is changed from 937208 to 484219. So I am confused is it okay to stop and restart the script without any temp file removed.

**Comment by aquaskyline** [comment]
LRSIM will redo the whole step 4 all over again. So if without any parameter change, the read countdown will still be 937208
